FROM district0x/base as dependencies
WORKDIR /app
COPY project.clj .
COPY resources/libs resources/libs
RUN lein deps

FROM dependencies as dependencies-full
WORKDIR /app
COPY . .

FROM dependencies-full as builder
WORKDIR /app
RUN lein solc once
RUN lein cljsbuild once "ui"

FROM district0x/base
EXPOSE 80
RUN apt-get --allow-releaseinfo-change update
RUN apt-get update -y \
    && apt-get install --no-install-recommends -y -q nginx

# you have to add custom nginx config in docker compose
# see our pipelines repository
# /etc/nginx/nginx.conf
# /etc/nginx/sites-enabled/district0x-tasks.io

WORKDIR /app
COPY --from=builder /app/resources/public/ .
CMD ["nginx", "-g", "daemon off"]

HEALTHCHECK --interval=5m --timeout=3s --retries=3 \
    CMD curl --output /dev/null --silent --head --fail -k http://localhost:80 || exit 1