FROM district0x/base as dependencies
WORKDIR /app
COPY project.clj .
COPY resources/libs resources/libs
RUN lein deps

FROM dependencies as dependencies-full
WORKDIR /app
COPY . .

FROM dependencies-full as builder
WORKDIR /app
RUN lein solc once
RUN lein cljsbuild once "ui"

FROM district0x/base
EXPOSE 80
RUN apt-get update -y \
    && apt-get install --no-install-recommends -y -q nginx
#COPY nginx.conf /etc/nginx/nginx.conf
#RUN wget --no-check-certificate -O X0X.html https://raw.githubusercontent.com/district0x/X0X/master/X0X.html \
#  && mv X0X.html /usr/share/nginx/html/X0X.html
#COPY district0x-tasks.io /etc/nginx/sites-available/district0x-tasks.io
#RUN ln -s -f /etc/nginx/sites-available/district0x-tasks.io /etc/nginx/sites-enabled/district0x-tasks.io
WORKDIR /app
COPY --from=builder /app/ .
CMD ["nginx", "-g", "daemon off;"]

HEALTHCHECK --interval=5m --timeout=3s --retries=3 \
    CMD curl --output /dev/null --silent --head --fail -k http://localhost:80 || exit 1