version: "3"
services:
  parity:
    image: parity/parity:stable
    ports:
    - 8545:8545
    volumes:
    - /tmp/parity-docker/testnet:/home/parity/.local/share/io.parity.ethereum/
    networks:
    - tasks-net
    command:
      --chain ropsten
      --base-path /home/parity/.local/share/io.parity.ethereum/
      --jsonrpc-apis 'web3,eth,net,parity,personal'
      --jsonrpc-interface all
      --jsonrpc-hosts all
      --jsonrpc-cors '*'
      --cache-size 1024
      --db-compaction ssd
      --mode active
      --jsonrpc-port 8545

  server:
    build:
      dockerfile: Dockerfile-server
    depends_on:
    - parity
    ports:
    - 6500:6500
    networks:
    - tasks-net

  ui:
    build:
      dockerfile: Dockerfile-ui
    depends_on:
    - parity
    - server
    ports:
    - 80:80
    networks:
    - tasks-net

  networks:
    tasks-net:
      driver: "bridge"